package:
  name: mapscape
  version: 1.10.0
source:
  git_url: https://github.com/maiasmith/mapscape.git
  git_rev: master
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r-cluster'
    - 'r-lattice'
    - 'r-matrix'
    - 'r-mgcv'
    - 'r-nlme'
    - 'r-survival'
    - 'r-htmlwidgets'
    - 'r-jsonlite'
    - 'r-base64enc'
    - 'r-stringr'
  run:
    - 'r-cluster'
    - 'r-lattice'
    - 'r-matrix'
    - 'r-mgcv'
    - 'r-nlme'
    - 'r-survival'
    - 'r-htmlwidgets'
    - 'r-jsonlite'
    - 'r-base64enc'
    - 'r-stringr'
#test:
#  commands:
#    - '$R -e "library(''mapscape'')"'
about:
  home: https://github.com/maiasmith/mapscape
  summary: 'Mapscape'

