package:
  name: vizutils
  version: 1.2

source:
  git_rev: master
  git_url: https://svn.bcgsc.ca/bitbucket/scm/~dgrewal/vizutils.git

build:
  number: 1

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy
    - intervaltree
    - pandas
    - matplotlib

test:
  commands:
    - vizutils_parse_museq --help
    - vizutils_parse_strelka --help
    - vizutils_parse_destruct --help
    - vizutils_parse_lumpy --help
    - vizutils_filter_low_mappability --help

about:
  home: https://svn.bcgsc.ca/bitbucket/scm/~dgrewal/vizutils
