package:
  name: bnpy
  version: '8019474'

source:
  git_url: https://bitbucket.org/dranew/bnpy-dev.git
  git_rev: 1a3a01a6ce2dc0df540cd1531c0d01e5cc57a1bd

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - scipy

build:
  number: 1

test:
  commands:

about:
  home: https://bitbucket.org/michaelchughes/bnpy-dev/
  summary: Bayesian nonparametric machine learning for python.