package:
  name: bioconductor-aneufinder
  version: 1.6.0
source:
  fn: AneuFinder_1.6.0.tar.gz
  url:
    - http://bioconductor.org/packages/3.6/bioc/src/contrib/AneuFinder_1.6.0.tar.gz
    - https://depot.galaxyproject.org/software/AneuFinder/AneuFinder_1.6.0_src_all.tar.gz
  md5: 48e96269b5a83e3ae0ea31e1d8ac25ca
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-aneufinderdata
    - bioconductor-bamsignals
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-dnacopy
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rhtslib
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - gcc
    - r-base
    - r-cowplot
    - r-doparallel
    - r-foreach
    - r-ggdendro
    - r-ggplot2
    - r-ggrepel
    - r-mclust
    - r-reordercluster
    - r-reshape2
  run:
    - bioconductor-aneufinderdata
    - bioconductor-bamsignals
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-dnacopy
    - bioconductor-genomeinfodb
    - bioconductor-genomicalignments
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rhtslib
    - bioconductor-rsamtools
    - bioconductor-s4vectors
    - r-base
    - r-cowplot
    - r-doparallel
    - r-foreach
    - r-ggdendro
    - r-ggplot2
    - r-ggrepel
    - r-mclust
    - r-reordercluster
    - r-reshape2
test:
  commands:
    - '$R -e "library(''AneuFinder'')"'
about:
  home: http://bioconductor.org/packages/3.6/bioc/html/AneuFinder.html
  license: Artistic-2.0
  summary: 'This package implements functions for CNV calling, plotting, export and
    analysis from whole-genome single cell sequencing data.'
