package:
  name: theta
  version: '0.7'

source:
  git_url: https://github.com/raphael-group/THetA.git
  git_rev: v0.7

requirements:
  build:
    - ant
  run:
    - bnpy

build:
  number: 1

test:
  commands:
    - 

about:
  home: http://compbio.cs.brown.edu/projects/theta/
  summary: Tumor Heterogeneity Analysis (THetA) is an algorithm that estimates the tumor purity and clonal/subclonal copy number aberrations directly from high-throughput DNA sequencing data.
