package:
  name: pvacseq
  version: 4.0.5

source:
  git_url: https://github.com/griffithlab/pVAC-Seq
  git_rev: v4.0.5

requirements:
  build:
    - python3
  run:
    - python3
    - numpy

build:
  number: 1

test:
  commands:

about:
  home: https://github.com/griffithlab/pVAC-Seq
  summary: A cancer immunotherapy pipeline
