package:
  name: hmmcopy_utils
  version: '0.0.1'

source:
  git_url: https://dranew@bitbucket.org/dranew/hmmcopy_utils.git
  git_rev: v0.0.1

build:
  number: 1

requirements:
  build:
    - cmake

test:
  commands:
    - gcCounter 2>&1 | grep Usage
    - mapCounter 2>&1 | grep Usage
    - readCounter 2>&1 | grep Usage

about:
  home: http://compbio.bccrc.ca/software/hmmcopy/
  summary: 'Utilities for HMMCopy'

