package:
  name: boost_lib
  version: '1.60.0'

source:
  fn: boost_1_60_0.tar.gz
  url: https://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz

requirements:
  build:
    - python

build:
  number: 1

about:
  home: http://www.boost.org
  license: Boost Software License
  summary: 'Library for boost c++'

