package:
  name: pypdf2
  version: 'v1.26.0'

source:
  git_url: https://github.com/mstamy2/PyPDF2
  git_rev: master

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/mstamy2/PyPDF2
  license: GPLv3
  summary: pdf toolkit for python
