package:
  name: clickclick
  version: "1.2.1"

source:
  fn: clickclick-1.2.1.tar.gz
  url: https://pypi.python.org/packages/6f/46/28462eb039bbce3651084d5260c50ab83dc3af0724626e6a81c93d950b2c/clickclick-1.2.1.tar.gz
  md5: bd7e136f0ed3516589795be5c60dc386
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - clickclick = clickclick:main
    #
    # Would create an entry point called clickclick that calls clickclick.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - click >=4.0
    - pyyaml >=3.11
    - flake8
    - six

  run:
    - python
    - click >=4.0
    - pyyaml >=3.11
    - flake8
    - six

test:
  # Python imports
  imports:
    - clickclick

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - pytest
    - pytest-cov
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/zalando/python-clickclick
  license: Apache Software License
  summary: 'Click utility functions'
  license_family: Apache

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
