package:
  name: lumpy-sv
  version: '0.2.11'

source:
  git_url: https://github.com/arq5x/lumpy-sv.git
  git_rev: v0.2.11

build:
  number: 1

test:
  commands:
    - delly --help 2>&1 | grep delly

about:
  home: https://github.com/tobiasrausch/delly
  license: GPLv3
  summary: Structural variant discovery by integrated paired-end and split-read analysis 