package:
  name: bicseq2-norm
  version: '0.2.4'

source:
  url: http://www.math.pku.edu.cn/teachers/xirb/downloads/software/BICseq2/BICseq2/NBICseq-norm_v0.2.4.tar.gz
  fn: NBICseq-norm_v0.2.4.tar.gz

requirements:
  build:
  run:

test:
  commands:

about:
  home: http://www.math.pku.edu.cn/teachers/xirb/downloads/software/BICseq2/BICseq2.html
