package:
  name: lumpy-sv
  version: '0.2.13'

source:
  git_url: https://github.com/arq5x/lumpy-sv.git
  git_rev: '0.2.13'

build:
  number: 3

requirements:
  run:
    - samblaster
    - python
    - gawk
    - pysam
    - numpy

test:
  commands:
    - lumpy 2>&1 | grep Usage
    - lumpyexpress 2>&1 | grep usage
    - lumpy_extractSplitReads_BwaMem 2>&1 | grep Usage

about:
  home: https://github.com/arq5x/lumpy-sv
  license: GPLv3
  summary: A general probabilistic framework for structural variant discovery
