package:
  name: delly
  version: '0.7.3'

source:
  git_url: https://github.com/amcpherson/delly.git
  git_rev: v0.7.3

build:
  number: 1

requirements:
  build:
    - boost_lib
    - htslib

test:
  commands:
    - delly --help 2>&1 | grep delly

about:
  home: https://github.com/tobiasrausch/delly
  license: GPLv3
  summary: Structural variant discovery by integrated paired-end and split-read analysis 
