package:
  name: delly
  version: '0.7.3'

source:
  fn: delly
  url: https://github.com/tobiasrausch/delly/releases/download/v0.7.3/delly_v0.7.3_linux_x86_64bit

build:
  number: 1

test:
  commands:
    - delly --help 2>&1 | grep delly

about:
  home: https://github.com/tobiasrausch/delly
  license: GPLv3
  summary: Structural variant discovery by integrated paired-end and split-read analysis 
