package:
  name: bioconductor-hmmcopy
  version: 1.12.0
source:
  fn: HMMcopy_1.12.0.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/HMMcopy_1.12.0.tar.gz
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-geneplotter'
    - 'bioconductor-iranges'
    - 'r >=3.1.0'
  run:
    - 'bioconductor-geneplotter'
    - 'bioconductor-iranges'
    - 'r >=3.1.0'
test:
  commands:
    - '$R -e "library(''HMMcopy'')"'
about:
  home: http://bioconductor.org/packages/HMMcopy/
  summary: 'Corrects GC and mappability biases for readcounts (i.e. coverage) in non-overlapping windows of fixed length
    for single whole genome samples, yielding a rough estimate of copy number for furthur analysis. Designed for rapid
    correction of high coverage whole genome tumour and normal samples.'
