package:
  name: circos_utils
  version: '0.0.1'
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r >=3.1.0'
    - 'r-circlize'
    - 'bioconductor-complexheatmap'
    -  'r-rcolorbrewer'
    - readline
  run:
    - 'r >=3.1.0'
    - 'r-circlize'
    - 'bioconductor-complexheatmap'
    - 'r-rcolorbrewer'
    - readline
test:
  commands:
    - 'R -e "library(circlize)"'
    - 'R -e "library(ComplexHeatmap)"'
    - 'R -e "library(RColorBrewer)"'

about:
  home: http://shahlab.ca
  summary: ''
