package:
  name: museq
  version: 4.3.10
source:
  - git_url: https://github.com/shahcompbio/mutationseq.git
    git_rev: master
    folder: museq
  - url: https://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.gz/download
    folder: boost
    fn: boost.tar.gz
build:
  number: 1
requirements:
  build:
    - python 2.7*
    - numpy
    - scipy
    - matplotlib
    - scikit-learn==0.20.3
    - intervaltree
  run:
    - python 2.7*
    - numpy
    - scipy
    - matplotlib
    - scikit-learn==0.20.3
    - intervaltree
test:
  commands:
    - 'museq --version'
about:
  home: https://github.com/shahcompbio/mutationseq/tree/v4.3.10
  summary: 'Software for somatic SNV detection using next generation sequencing (NGS) data.'

