package:
  name: titan_wgs_utils
  version: 1.10.0
source:
  - git_url: https://github.com/shahcompbio/titan_wgs_utils.git
    folder: titan_wgs_utils
build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
  run:
test:
  commands:
    - '[[ -f correctReads.R ]] && echo "This file exists"'
    - '[[ -f createTITANsegmentfiles.pl ]] && echo "This file exists"'
    - '[[ -f parse_titan_segments.py ]] && echo "This file exists"'
    - '[[ -f  plot_titan.R ]] && echo "This file exists"'
    - '[[ -f titan.R ]] && echo "This file exists"'
about:
  home: http://bioconductor.org/packages/TitanCNA/
  summary: 'Utility scripts for titan.'
